spring:
  data:
    mongodb:
      uri: mongodb+srv://irishmjn_db_user:ZcW7g36TXsdJg5k8@cluster0.zebo8lr.mongodb.net/journaldb?retryWrites=true&w=majority
      database: journaldb
      auto-index-creation: true
  app:
    env: dev
server:
  port: 8080
  servlet:
    context-path: /journal