#spring.application.name=myFirstProject
#//spring.data.mongodb.uri=mongodb+srv://irishmjn_db_user:ZcW7g36TXsdJg5k8@cluster0.zebo8lr.mongodb.net/?appName=Cluster0
#spring.data.mongodb.uri=mongodb+srv://irishmjn_db_user:ZcW7g36TXsdJg5k8@cluster0.zebo8lr.mongodb.net/journaldb
#//spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true